### ISSUE TITLE
app crash when try to open

### ISSUE THREAD

**Issue by muhammadarif1** [ttdyce/NHentaiViewer#1]
**Describe the bug**
app crash when try to open
**To Reproduce**
-download and open the app and note the error
**Expected behavior**
i expect i can open and use the as well
**Screenshots**
https://youtu.be/90HY0bygULE
*

**Smartphone (please complete the following information):**
 - Device: [e.g. oppo neo 5]
 - OS: [e.g. android 5.1]
 - Version [e.g. latest realeas signed apk]

**Additional context**
```FATAL EXCEPTION: main
Process: personal.ttd.nhviewer, PID: 5987
java.lang.RuntimeException: Unable to start activity ComponentInfo{personal.ttd.nhviewer/personal.ttd.nhviewer.Controller.MainActivity}: java.lang.NullPointerException: Attempt to get length of null array
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2525)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2617)
	at android.app.ActivityThread.access$800(ActivityThread.java:182)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1474)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:218)
	at android.app.ActivityThread.main(ActivityThread.java:5657)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:990)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:785)
Caused by: java.lang.NullPointerException: Attempt to get length of null array
	at personal.ttd.nhviewer.Model.Saver.JSONSaver.getCollectionList(JSONSaver.java:225)
	at personal.ttd.nhviewer.Model.comic.Collection.loadCollection(Collection.java:55)
	at personal.ttd.nhviewer.Controller.MainActivity.initCollection(MainActivity.java:225)
	at personal.ttd.nhviewer.Controller.MainActivity.init(MainActivity.java:129)
	at personal.ttd.nhviewer.Controller.MainActivity.onCreate(MainActivity.java:118)
	at android.app.Activity.performCreate(Activity.java:6135)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1112)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2472)
	... 10 more```

**Comment by ttdyce** [comment]
It is a fixed bug. Try the latest version
https://github.com/ttdyce/NHentaiViewer/releases/tag/1.0.1

**Comment by muhammadarif1** [comment]
It work now

**Comment by ttdyce** [comment]
Ok

**Comment by 00dark** [comment]
Comics not open.
It's say's "unable to connect to the site" always
What should I do???

**Comment by ttdyce** [comment]
> Comics not open.
> 
> It's say's "unable to connect to the site" always
> 
> What should I do???
> 
> 

Since this issue is about an older version that is no longer supported, what version you are running?

Thanks
