### ISSUE TITLE
app will crash if we click on tags option

### ISSUE THREAD

**Issue by muhammadarif1** [ttdyce/NHentaiViewer#2]
**Describe the bug**
app will crash if we click on "tags"option
**To Reproduce**
1. install and open the app
2. click on 3 line in the left side
3. then click on tags" option
**Screenshots**
https://youtu.be/B0fOBhY0LUk

**Smartphone (please complete the following information):**
 - Device: [e.g. oppo neo 5]
 - OS: [e.g. android 6.1]
 - Version [e.g. 1.0.1]

**Expected behavior**
app will show hentai by taggings
**Exception thrown**
```FATAL EXCEPTION: main
Process: personal.ttd.nhviewer, PID: 30666
java.lang.StringIndexOutOfBoundsException: length=0; index=0
	at java.lang.String.indexAndLength(String.java:500)
	at java.lang.String.charAt(String.java:494)
	at personal.ttd.nhviewer.Model.tag.TagManager.getTagRequired(TagManager.java:30)
	at personal.ttd.nhviewer.Controller.fragment.TagFragment.refreshListData(TagFragment.java:186)
	at personal.ttd.nhviewer.Controller.fragment.TagFragment.initList(TagFragment.java:173)
	at personal.ttd.nhviewer.Controller.fragment.TagFragment.onViewCreated(TagFragment.java:68)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1471)
	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
	at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:802)
	at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
	at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
	at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:733)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:218)
	at android.app.ActivityThread.main(ActivityThread.java:5657)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:990)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:785)```

**Comment by ttdyce** [comment]
I can't reproduce this error on my own but I have added a empty set checking on that function. 
You may try it here
[app-debug.zip](https://github.com/ttdyce/NHentaiViewer/files/3377887/app-debug.zip)

**Comment by muhammadarif1** [comment]
try whit this way
-open the app
- click on tags option
-click + button
- in tag name dont type anything, just click add and you will see the error

**Comment by ttdyce** [comment]
Thank you, I have fixed it. 
You can try it here and I will upload it to master later. 
[app-debug.zip](https://github.com/ttdyce/NHentaiViewer/files/3378006/app-debug.zip)
