### ISSUE TITLE
The app crashed when I tried to open the hentai after removing it from the favorite list.

### ISSUE THREAD

**Issue by sagorahmed** [ttdyce/NHentaiViewer#3]
**Describe the bug**
When I tried to open hentai after removing it from the favorite list, then the app crashed.

**To Reproduce**
1. Open the app.
2. Click on the love icon to add it as your favorite.
3. Now, swipe to the right to see your favorite list.
4. Then, press the love button again, the app will ask your permission to remove it. Press yes.
5. At last click on that hentai to open it and notice the crash.

**Expected behavior**
I expected that I could open the hentai after removing it from my favorite list or the hentai would disappear from the favorite list after removing.

**Screenshots**
https://www.youtube.com/watch?v=TXvJYyflFLo

**Smartphone (please complete the following information):**
 - Device: Samsung A5
 - OS: Android 6.0.1
 - App Version: 1.0.2

**Logcat**
```
E AndroidRuntime: FATAL EXCEPTION: main

07-19 11:46:38.275 10688 10688 E AndroidRuntime: Process: personal.ttd.nhviewer, PID: 10688

07-19 11:46:38.275 10688 10688 E AndroidRuntime: java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0

07-19 11:46:38.275 10688 10688 E AndroidRuntime: 	at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)

07-19 11:46:38.275 10688 10688 E AndroidRuntime: 	at java.util.ArrayList.get(ArrayList.java:308)

07-19 11:46:38.275 10688 10688 E AndroidRuntime: 	at personal.ttd.nhviewer.Controller.fragment.base.ComicListFragment$ComicListAdapter.onListItemClick(ComicListFragment.java:182)

07-19 11:46:38.275 10688 10688 E AndroidRuntime: 	at personal.ttd.nhviewer.Controller.fragment.base.BaseListFragment$BaseListAdapter$1.onClick(BaseListFragment.java:353)

07-19 11:46:38.275 10688 10688 E AndroidRuntime: 	at android.view.View.performClick(View.java:5714)

07-19 11:46:38.275 10688 10688 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:22589)

07-19 11:46:38.275 10688 10688 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)

07-19 11:46:38.275 10688 10688 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)

07-19 11:46:38.275 10688 10688 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)

07-19 11:46:38.275 10688 10688 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7325)

07-19 11:46:38.275 10688 10688 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)

07-19 11:46:38.275 10688 10688 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)

07-19 11:46:38.275 10688 10688 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by ttdyce** [comment]
Thank you for your report, I will upload a new version later.

**Comment by ttdyce** [comment]
The new version is committed and uploaded.

**Comment by sagorahmed** [comment]
Thanks for fixing the issue.
