### ISSUE TITLE
The app crashed when I clicked on history after deleting it from the collection menu

### ISSUE THREAD

**Issue by sagorahmed** [ttdyce/NHentaiViewer#7]
**Describe the bug**
When I tried to click on the "history" option after deleting history from the collection option, then the app crashed.

**To Reproduce**
1. Open the app.
2. Go to the main menu of the app and click on the "Collection".
3. You will see two tabs. Tap and hold the "history" and click on the delete icon to delete it.
4. Now once again go to the app's main menu and try to go to the "History" option and see an error.

**Expected behavior**
I expected that I could click on history after deleting it from the collection menu without getting any trouble.

**Screenshots**
![v](https://media.giphy.com/media/f3pLexLSM9ljgURyIJ/giphy.gif)

**Information:**
 - Device: Samsung A5
 - OS: Android 6.0.1
 - Version 1.0.3

**Logcat**
```
07-27 12:48:29.182  5007  5007 D AndroidRuntime: Shutting down VM

07-27 12:48:29.182  5007  5007 E AndroidRuntime: FATAL EXCEPTION: main

07-27 12:48:29.182  5007  5007 E AndroidRuntime: Process: personal.ttd.nhviewer, PID: 5007

07-27 12:48:29.182  5007  5007 E AndroidRuntime: java.lang.NullPointerException: name == null

07-27 12:48:29.182  5007  5007 E AndroidRuntime: 	at java.io.File.<init>(File.java:146)

07-27 12:48:29.182  5007  5007 E AndroidRuntime: 	at java.io.File.<init>(File.java:118)

07-27 12:48:29.182  5007  5007 E AndroidRuntime: 	at personal.ttd.nhviewer.Model.Saver.JSONSaver.getFile(JSONSaver.java:411)

07-27 12:48:29.182  5007  5007 E AndroidRuntime: 	at personal.ttd.nhviewer.Model.Saver.JSONSaver.getJSONArr(JSONSaver.java:269)

07-27 12:48:29.182  5007  5007 E AndroidRuntime: 	at personal.ttd.nhviewer.Model.Saver.JSONSaver.getCollection(JSONSaver.java:116)

07-27 12:48:29.182  5007  5007 E AndroidRuntime: 	at personal.ttd.nhviewer.Model.Saver.JSONSaver.getHistory(JSONSaver.java:68)

07-27 12:48:29.182  5007  5007 E AndroidRuntime: 	at personal.ttd.nhviewer.Model.comic.ComicMaker.getComicListHistory(ComicMaker.java:31)

07-27 12:48:29.182  5007  5007 E AndroidRuntime: 	at personal.ttd.nhviewer.Controller.fragment.HistoryFragment.setList(HistoryFragment.java:24)

07-27 12:48:29.182  5007  5007 E AndroidRuntime: 	at personal.ttd.nhviewer.Controller.fragment.base.BaseListFragment.onViewCreated(BaseListFragment.java:95)

07-27 12:48:29.182  5007  5007 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1471)

07-27 12:48:29.182  5007  5007 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)

07-27 12:48:29.182  5007  5007 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)

07-27 12:48:29.182  5007  5007 E AndroidRuntime: 	at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:802)

07-27 12:48:29.182  5007  5007 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)

07-27 12:48:29.182  5007  5007 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)

07-27 12:48:29.182  5007  5007 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)

07-27 12:48:29.182  5007  5007 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)

07-27 12:48:29.182  5007  5007 E AndroidRuntime: 	at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:733)

07-27 12:48:29.182  5007  5007 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)

07-27 12:48:29.182  5007  5007 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)

07-27 12:48:29.182  5007  5007 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)

07-27 12:48:29.182  5007  5007 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7325)

07-27 12:48:29.182  5007  5007 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)

07-27 12:48:29.182  5007  5007 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)

07-27 12:48:29.182  5007  5007 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

07-27 12:48:29.182  2680  3320 W VirtualScreenManagerService: moveTaskBackToDisplayIfNeeded(): root is not base activity
```

**Comment by ttdyce** [comment]
Thanks for your report. 
I just fixed it in the latest version, try if it works!

**Comment by sagorahmed** [comment]
Hi.
This issue is not occurring anymore in the latest version of the app.
Thank for solving the issue!
